<?php

namespace Database\Seeders;

use App\Models\DesaKelurahan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class DesaKelurahanSeeder extends Seeder
{
    public function run()
    {
        // // Disable foreign key constraints (PostgreSQL way)
        // Schema::disableForeignKeyConstraints();

        // // Truncate the table
        // DesaKelurahan::truncate();

        // // Re-enable foreign key constraints
        // Schema::enableForeignKeyConstraints();

        // Disable foreign key constraints (MySQL way)
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Truncate the table
        DesaKelurahan::truncate();

        // Re-enable foreign key constraints
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $desaKelurahans = [
            // Sleman (id: 210, 17 kecamatan, 86 desa/kelurahan)
            ['id_desa_kelurahan' => 43172, 'id_kecamatan' => 2948, 'nama_desa_kelurahan' => 'Sumberagung'],
            ['id_desa_kelurahan' => 43173, 'id_kecamatan' => 2948, 'nama_desa_kelurahan' => 'Moyudan'],
            ['id_desa_kelurahan' => 43174, 'id_kecamatan' => 2948, 'nama_desa_kelurahan' => 'Sumbermulyo'],
            ['id_desa_kelurahan' => 43175, 'id_kecamatan' => 2948, 'nama_desa_kelurahan' => 'Tegalsari'],
            ['id_desa_kelurahan' => 43176, 'id_kecamatan' => 2948, 'nama_desa_kelurahan' => 'Sumberrejo'],
            ['id_desa_kelurahan' => 43177, 'id_kecamatan' => 2949, 'nama_desa_kelurahan' => 'Sendangmulyo'],
            ['id_desa_kelurahan' => 43178, 'id_kecamatan' => 2949, 'nama_desa_kelurahan' => 'Minggir'],
            ['id_desa_kelurahan' => 43179, 'id_kecamatan' => 2949, 'nama_desa_kelurahan' => 'Karanglo'],
            ['id_desa_kelurahan' => 43180, 'id_kecamatan' => 2949, 'nama_desa_kelurahan' => 'Sendangrejo'],
            ['id_desa_kelurahan' => 43181, 'id_kecamatan' => 2949, 'nama_desa_kelurahan' => 'Demangan'],
            ['id_desa_kelurahan' => 43182, 'id_kecamatan' => 2950, 'nama_desa_kelurahan' => 'Margodadi'],
            ['id_desa_kelurahan' => 43183, 'id_kecamatan' => 2950, 'nama_desa_kelurahan' => 'Seyegan'],
            ['id_desa_kelurahan' => 43184, 'id_kecamatan' => 2950, 'nama_desa_kelurahan' => 'Margomulyo'],
            ['id_desa_kelurahan' => 43185, 'id_kecamatan' => 2950, 'nama_desa_kelurahan' => 'Margoagung'],
            ['id_desa_kelurahan' => 43186, 'id_kecamatan' => 2950, 'nama_desa_kelurahan' => 'Wedomartani'],
            ['id_desa_kelurahan' => 43187, 'id_kecamatan' => 2951, 'nama_desa_kelurahan' => 'Sidorejo'],
            ['id_desa_kelurahan' => 43188, 'id_kecamatan' => 2951, 'nama_desa_kelurahan' => 'Godean'],
            ['id_desa_kelurahan' => 43189, 'id_kecamatan' => 2951, 'nama_desa_kelurahan' => 'Sidoarum'],
            ['id_desa_kelurahan' => 43190, 'id_kecamatan' => 2951, 'nama_desa_kelurahan' => 'Sidoagung'],
            ['id_desa_kelurahan' => 43191, 'id_kecamatan' => 2951, 'nama_desa_kelurahan' => 'Sidomulyo'],
            ['id_desa_kelurahan' => 43192, 'id_kecamatan' => 2952, 'nama_desa_kelurahan' => 'Banyuraden'],
            ['id_desa_kelurahan' => 43193, 'id_kecamatan' => 2952, 'nama_desa_kelurahan' => 'Gamping'],
            ['id_desa_kelurahan' => 43194, 'id_kecamatan' => 2952, 'nama_desa_kelurahan' => 'Trihanggo'],
            ['id_desa_kelurahan' => 43195, 'id_kecamatan' => 2952, 'nama_desa_kelurahan' => 'Ambarukmo'],
            ['id_desa_kelurahan' => 43196, 'id_kecamatan' => 2952, 'nama_desa_kelurahan' => 'Nogotirto'],
            ['id_desa_kelurahan' => 43197, 'id_kecamatan' => 2953, 'nama_desa_kelurahan' => 'Sinduharjo'],
            ['id_desa_kelurahan' => 43198, 'id_kecamatan' => 2953, 'nama_desa_kelurahan' => 'Mlati'],
            ['id_desa_kelurahan' => 43199, 'id_kecamatan' => 2953, 'nama_desa_kelurahan' => 'Sendangadi'],
            ['id_desa_kelurahan' => 43200, 'id_kecamatan' => 2953, 'nama_desa_kelurahan' => 'Tirtoadi'],
            ['id_desa_kelurahan' => 43201, 'id_kecamatan' => 2953, 'nama_desa_kelurahan' => 'Tlogoadi'],
            ['id_desa_kelurahan' => 43202, 'id_kecamatan' => 2954, 'nama_desa_kelurahan' => 'Caturtunggal'],
            ['id_desa_kelurahan' => 43203, 'id_kecamatan' => 2954, 'nama_desa_kelurahan' => 'Depok'],
            ['id_desa_kelurahan' => 43204, 'id_kecamatan' => 2954, 'nama_desa_kelurahan' => 'Maguwoharjo'],
            ['id_desa_kelurahan' => 43205, 'id_kecamatan' => 2954, 'nama_desa_kelurahan' => 'Condongcatur'],
            ['id_desa_kelurahan' => 43206, 'id_kecamatan' => 2955, 'nama_desa_kelurahan' => 'Tegaltirto'],
            ['id_desa_kelurahan' => 43207, 'id_kecamatan' => 2955, 'nama_desa_kelurahan' => 'Berbah'],
            ['id_desa_kelurahan' => 43208, 'id_kecamatan' => 2955, 'nama_desa_kelurahan' => 'Kalitirto'],
            ['id_desa_kelurahan' => 43209, 'id_kecamatan' => 2955, 'nama_desa_kelurahan' => 'Jogotirto'],
            ['id_desa_kelurahan' => 43210, 'id_kecamatan' => 2956, 'nama_desa_kelurahan' => 'Bokoharjo'],
            ['id_desa_kelurahan' => 43211, 'id_kecamatan' => 2956, 'nama_desa_kelurahan' => 'Prambanan'],
            ['id_desa_kelurahan' => 43212, 'id_kecamatan' => 2956, 'nama_desa_kelurahan' => 'Sumberharjo'],
            ['id_desa_kelurahan' => 43213, 'id_kecamatan' => 2956, 'nama_desa_kelurahan' => 'Wukirharjo'],
            ['id_desa_kelurahan' => 43214, 'id_kecamatan' => 2957, 'nama_desa_kelurahan' => 'Tamanmartani'],
            ['id_desa_kelurahan' => 43215, 'id_kecamatan' => 2957, 'nama_desa_kelurahan' => 'Kalasan'],
            ['id_desa_kelurahan' => 43216, 'id_kecamatan' => 2957, 'nama_desa_kelurahan' => 'Purwomartani'],
            ['id_desa_kelurahan' => 43217, 'id_kecamatan' => 2957, 'nama_desa_kelurahan' => 'Selomartani'],
            ['id_desa_kelurahan' => 43218, 'id_kecamatan' => 2958, 'nama_desa_kelurahan' => 'Widodomartani'],
            ['id_desa_kelurahan' => 43219, 'id_kecamatan' => 2958, 'nama_desa_kelurahan' => 'Ngemplak'],
            ['id_desa_kelurahan' => 43220, 'id_kecamatan' => 2958, 'nama_desa_kelurahan' => 'Bimomartani'],
            ['id_desa_kelurahan' => 43221, 'id_kecamatan' => 2958, 'nama_desa_kelurahan' => 'Umbulmartani'],
            ['id_desa_kelurahan' => 43222, 'id_kecamatan' => 2959, 'nama_desa_kelurahan' => 'Sardonoharjo'],
            ['id_desa_kelurahan' => 43223, 'id_kecamatan' => 2959, 'nama_desa_kelurahan' => 'Ngaglik'],
            ['id_desa_kelurahan' => 43224, 'id_kecamatan' => 2959, 'nama_desa_kelurahan' => 'Sukoharjo'],
            ['id_desa_kelurahan' => 43225, 'id_kecamatan' => 2959, 'nama_desa_kelurahan' => 'Minomartani'],
            ['id_desa_kelurahan' => 43226, 'id_kecamatan' => 2959, 'nama_desa_kelurahan' => 'Donoharjo'],
            ['id_desa_kelurahan' => 43227, 'id_kecamatan' => 2960, 'nama_desa_kelurahan' => 'Triharjo'],
            ['id_desa_kelurahan' => 43228, 'id_kecamatan' => 2960, 'nama_desa_kelurahan' => 'Sleman'],
            ['id_desa_kelurahan' => 43229, 'id_kecamatan' => 2960, 'nama_desa_kelurahan' => 'Pandowoharjo'],
            ['id_desa_kelurahan' => 43230, 'id_kecamatan' => 2960, 'nama_desa_kelurahan' => 'Caturharjo'],
            ['id_desa_kelurahan' => 43231, 'id_kecamatan' => 2960, 'nama_desa_kelurahan' => 'Tridadi'],
            ['id_desa_kelurahan' => 43232, 'id_kecamatan' => 2961, 'nama_desa_kelurahan' => 'Tamanan'],
            ['id_desa_kelurahan' => 43233, 'id_kecamatan' => 2961, 'nama_desa_kelurahan' => 'Tempel'],
            ['id_desa_kelurahan' => 43234, 'id_kecamatan' => 2961, 'nama_desa_kelurahan' => 'Banyurejo'],
            ['id_desa_kelurahan' => 43235, 'id_kecamatan' => 2961, 'nama_desa_kelurahan' => 'Merdikorejo'],
            ['id_desa_kelurahan' => 43236, 'id_kecamatan' => 2961, 'nama_desa_kelurahan' => 'Margorejo'],
            ['id_desa_kelurahan' => 43237, 'id_kecamatan' => 2962, 'nama_desa_kelurahan' => 'Girikerto'],
            ['id_desa_kelurahan' => 43238, 'id_kecamatan' => 2962, 'nama_desa_kelurahan' => 'Turi'],
            ['id_desa_kelurahan' => 43239, 'id_kecamatan' => 2962, 'nama_desa_kelurahan' => 'Wonosari'],
            ['id_desa_kelurahan' => 43240, 'id_kecamatan' => 2962, 'nama_desa_kelurahan' => 'Bangunkerto'],
            ['id_desa_kelurahan' => 43241, 'id_kecamatan' => 2962, 'nama_desa_kelurahan' => 'Donokerto'],
            ['id_desa_kelurahan' => 43242, 'id_kecamatan' => 2963, 'nama_desa_kelurahan' => 'Harjobinangun'],
            ['id_desa_kelurahan' => 43243, 'id_kecamatan' => 2963, 'nama_desa_kelurahan' => 'Pakem'],
            ['id_desa_kelurahan' => 43244, 'id_kecamatan' => 2963, 'nama_desa_kelurahan' => 'Candibinangun'],
            ['id_desa_kelurahan' => 43245, 'id_kecamatan' => 2963, 'nama_desa_kelurahan' => 'Pakembinangun'],
            ['id_desa_kelurahan' => 43246, 'id_kecamatan' => 2963, 'nama_desa_kelurahan' => 'Hargobinangun'],
            ['id_desa_kelurahan' => 43247, 'id_kecamatan' => 2964, 'nama_desa_kelurahan' => 'Glagaharjo'],
            ['id_desa_kelurahan' => 43248, 'id_kecamatan' => 2964, 'nama_desa_kelurahan' => 'Cangkringan'],
            ['id_desa_kelurahan' => 43249, 'id_kecamatan' => 2964, 'nama_desa_kelurahan' => 'Wukirsari'],
            ['id_desa_kelurahan' => 43250, 'id_kecamatan' => 2964, 'nama_desa_kelurahan' => 'Umbulharjo'],
            ['id_desa_kelurahan' => 43251, 'id_kecamatan' => 2964, 'nama_desa_kelurahan' => 'Kepuharjo'],

            // Bantul (id: 211, 17 kecamatan, 75 desa/kelurahan)
            ['id_desa_kelurahan' => 43252, 'id_kecamatan' => 2965, 'nama_desa_kelurahan' => 'Triwidadi'],
            ['id_desa_kelurahan' => 43253, 'id_kecamatan' => 2965, 'nama_desa_kelurahan' => 'Srandakan'],
            ['id_desa_kelurahan' => 43254, 'id_kecamatan' => 2965, 'nama_desa_kelurahan' => 'Poncosari'],
            ['id_desa_kelurahan' => 43255, 'id_kecamatan' => 2965, 'nama_desa_kelurahan' => 'Trimulyo'],
            ['id_desa_kelurahan' => 43256, 'id_kecamatan' => 2966, 'nama_desa_kelurahan' => 'Murtigading'],
            ['id_desa_kelurahan' => 43257, 'id_kecamatan' => 2966, 'nama_desa_kelurahan' => 'Sanden'],
            ['id_desa_kelurahan' => 43258, 'id_kecamatan' => 2966, 'nama_desa_kelurahan' => 'Gadingsari'],
            ['id_desa_kelurahan' => 43259, 'id_kecamatan' => 2966, 'nama_desa_kelurahan' => 'Srigeude'],
            ['id_desa_kelurahan' => 43260, 'id_kecamatan' => 2967, 'nama_desa_kelurahan' => 'Tirtomulyo'],
            ['id_desa_kelurahan' => 43261, 'id_kecamatan' => 2967, 'nama_desa_kelurahan' => 'Kretek'],
            ['id_desa_kelurahan' => 43262, 'id_kecamatan' => 2967, 'nama_desa_kelurahan' => 'Parangtritis'],
            ['id_desa_kelurahan' => 43263, 'id_kecamatan' => 2967, 'nama_desa_kelurahan' => 'Donotirto'],
            ['id_desa_kelurahan' => 43264, 'id_kecamatan' => 2968, 'nama_desa_kelurahan' => 'Pananggungan'],
            ['id_desa_kelurahan' => 43265, 'id_kecamatan' => 2968, 'nama_desa_kelurahan' => 'Pundong'],
            ['id_desa_kelurahan' => 43266, 'id_kecamatan' => 2968, 'nama_desa_kelurahan' => 'Srihardono'],
            ['id_desa_kelurahan' => 43267, 'id_kecamatan' => 2968, 'nama_desa_kelurahan' => 'Seloharjo'],
            ['id_desa_kelurahan' => 43268, 'id_kecamatan' => 2969, 'nama_desa_kelurahan' => 'Sidomulyo'],
            ['id_desa_kelurahan' => 43269, 'id_kecamatan' => 2969, 'nama_desa_kelurahan' => 'Bambanglipuro'],
            ['id_desa_kelurahan' => 43270, 'id_kecamatan' => 2969, 'nama_desa_kelurahan' => 'Mulyodadi'],
            ['id_desa_kelurahan' => 43271, 'id_kecamatan' => 2969, 'nama_desa_kelurahan' => 'Sumbermulyo'],
            ['id_desa_kelurahan' => 43272, 'id_kecamatan' => 2970, 'nama_desa_kelurahan' => 'Pandak'],
            ['id_desa_kelurahan' => 43273, 'id_kecamatan' => 2970, 'nama_desa_kelurahan' => 'Caturharjo'],
            ['id_desa_kelurahan' => 43274, 'id_kecamatan' => 2970, 'nama_desa_kelurahan' => 'Wijirejo'],
            ['id_desa_kelurahan' => 43275, 'id_kecamatan' => 2970, 'nama_desa_kelurahan' => 'Gilangharjo'],
            ['id_desa_kelurahan' => 43276, 'id_kecamatan' => 2971, 'nama_desa_kelurahan' => 'Bantul'],
            ['id_desa_kelurahan' => 43277, 'id_kecamatan' => 2971, 'nama_desa_kelurahan' => 'Palbapang'],
            ['id_desa_kelurahan' => 43278, 'id_kecamatan' => 2971, 'nama_desa_kelurahan' => 'Ringinharjo'],
            ['id_desa_kelurahan' => 43279, 'id_kecamatan' => 2971, 'nama_desa_kelurahan' => 'Sabdodadi'],
            ['id_desa_kelurahan' => 43280, 'id_kecamatan' => 2972, 'nama_desa_kelurahan' => 'Bangunjiwo'],
            ['id_desa_kelurahan' => 43281, 'id_kecamatan' => 2972, 'nama_desa_kelurahan' => 'Jetis'],
            ['id_desa_kelurahan' => 43282, 'id_kecamatan' => 2972, 'nama_desa_kelurahan' => 'Canden'],
            ['id_desa_kelurahan' => 43283, 'id_kecamatan' => 2972, 'nama_desa_kelurahan' => 'Sumberagung'],
            ['id_desa_kelurahan' => 43284, 'id_kecamatan' => 2973, 'nama_desa_kelurahan' => 'Imogiri'],
            ['id_desa_kelurahan' => 43285, 'id_kecamatan' => 2973, 'nama_desa_kelurahan' => 'Karangtalun'],
            ['id_desa_kelurahan' => 43286, 'id_kecamatan' => 2973, 'nama_desa_kelurahan' => 'Wukirsari'],
            ['id_desa_kelurahan' => 43287, 'id_kecamatan' => 2973, 'nama_desa_kelurahan' => 'Girirejo'],
            ['id_desa_kelurahan' => 43288, 'id_kecamatan' => 2974, 'nama_desa_kelurahan' => 'Dlingo'],
            ['id_desa_kelurahan' => 43289, 'id_kecamatan' => 2974, 'nama_desa_kelurahan' => 'Temuwuh'],
            ['id_desa_kelurahan' => 43290, 'id_kecamatan' => 2974, 'nama_desa_kelurahan' => 'Jatimulyo'],
            ['id_desa_kelurahan' => 43291, 'id_kecamatan' => 2974, 'nama_desa_kelurahan' => 'Mangunan'],
            ['id_desa_kelurahan' => 43292, 'id_kecamatan' => 2975, 'nama_desa_kelurahan' => 'Pleret'],
            ['id_desa_kelurahan' => 43293, 'id_kecamatan' => 2975, 'nama_desa_kelurahan' => 'Wonokromo'],
            ['id_desa_kelurahan' => 43294, 'id_kecamatan' => 2975, 'nama_desa_kelurahan' => 'Bawuran'],
            ['id_desa_kelurahan' => 43295, 'id_kecamatan' => 2975, 'nama_desa_kelurahan' => 'Segoroyoso'],
            ['id_desa_kelurahan' => 43296, 'id_kecamatan' => 2976, 'nama_desa_kelurahan' => 'Piyungan'],
            ['id_desa_kelurahan' => 43297, 'id_kecamatan' => 2976, 'nama_desa_kelurahan' => 'Srimulyo'],
            ['id_desa_kelurahan' => 43298, 'id_kecamatan' => 2976, 'nama_desa_kelurahan' => 'Srimartani'],
            ['id_desa_kelurahan' => 43299, 'id_kecamatan' => 2976, 'nama_desa_kelurahan' => 'Bokoharjo'],
            ['id_desa_kelurahan' => 43300, 'id_kecamatan' => 2977, 'nama_desa_kelurahan' => 'Banguntapan'],
            ['id_desa_kelurahan' => 43301, 'id_kecamatan' => 2977, 'nama_desa_kelurahan' => 'Jagalan'],
            ['id_desa_kelurahan' => 43302, 'id_kecamatan' => 2977, 'nama_desa_kelurahan' => 'Singosaren'],
            ['id_desa_kelurahan' => 43303, 'id_kecamatan' => 2977, 'nama_desa_kelurahan' => 'Tamanan'],
            ['id_desa_kelurahan' => 43304, 'id_kecamatan' => 2978, 'nama_desa_kelurahan' => 'Sewon'],
            ['id_desa_kelurahan' => 43305, 'id_kecamatan' => 2978, 'nama_desa_kelurahan' => 'Panggungharjo'],
            ['id_desa_kelurahan' => 43306, 'id_kecamatan' => 2978, 'nama_desa_kelurahan' => 'Pendowoharjo'],
            ['id_desa_kelurahan' => 43307, 'id_kecamatan' => 2978, 'nama_desa_kelurahan' => 'Timbulharjo'],
            ['id_desa_kelurahan' => 43308, 'id_kecamatan' => 2979, 'nama_desa_kelurahan' => 'Kasihan'],
            ['id_desa_kelurahan' => 43309, 'id_kecamatan' => 2979, 'nama_desa_kelurahan' => 'Tamantirto'],
            ['id_desa_kelurahan' => 43310, 'id_kecamatan' => 2979, 'nama_desa_kelurahan' => 'Ngestiharjo'],
            ['id_desa_kelurahan' => 43311, 'id_kecamatan' => 2979, 'nama_desa_kelurahan' => 'Bangunjiwo'],
            ['id_desa_kelurahan' => 43312, 'id_kecamatan' => 2980, 'nama_desa_kelurahan' => 'Pajangan'],
            ['id_desa_kelurahan' => 43313, 'id_kecamatan' => 2980, 'nama_desa_kelurahan' => 'Guwosari'],
            ['id_desa_kelurahan' => 43314, 'id_kecamatan' => 2980, 'nama_desa_kelurahan' => 'Sendangsari'],
            ['id_desa_kelurahan' => 43315, 'id_kecamatan' => 2980, 'nama_desa_kelurahan' => 'Triharjo'],
            ['id_desa_kelurahan' => 43316, 'id_kecamatan' => 2981, 'nama_desa_kelurahan' => 'Sedayu'],
            ['id_desa_kelurahan' => 43317, 'id_kecamatan' => 2981, 'nama_desa_kelurahan' => 'Argomulyo'],
            ['id_desa_kelurahan' => 43318, 'id_kecamatan' => 2981, 'nama_desa_kelurahan' => 'Argosari'],
            ['id_desa_kelurahan' => 43319, 'id_kecamatan' => 2981, 'nama_desa_kelurahan' => 'Argodadi'],

            // Yogyakarta (id: 212, 14 kecamatan, 45 kelurahan)
            ['id_desa_kelurahan' => 43320, 'id_kecamatan' => 2982, 'nama_desa_kelurahan' => 'Suryodiningratan'],
            ['id_desa_kelurahan' => 43321, 'id_kecamatan' => 2982, 'nama_desa_kelurahan' => 'Purbayan'],
            ['id_desa_kelurahan' => 43322, 'id_kecamatan' => 2982, 'nama_desa_kelurahan' => 'Mantrijeron'],
            ['id_desa_kelurahan' => 43323, 'id_kecamatan' => 2983, 'nama_desa_kelurahan' => 'Kadipaten'],
            ['id_desa_kelurahan' => 43324, 'id_kecamatan' => 2983, 'nama_desa_kelurahan' => 'Patehan'],
            ['id_desa_kelurahan' => 43325, 'id_kecamatan' => 2983, 'nama_desa_kelurahan' => 'Panembahan'],
            ['id_desa_kelurahan' => 43326, 'id_kecamatan' => 2984, 'nama_desa_kelurahan' => 'Wirogunan'],
            ['id_desa_kelurahan' => 43327, 'id_kecamatan' => 2984, 'nama_desa_kelurahan' => 'Brontokusuman'],
            ['id_desa_kelurahan' => 43328, 'id_kecamatan' => 2984, 'nama_desa_kelurahan' => 'Keparakan'],
            ['id_desa_kelurahan' => 43329, 'id_kecamatan' => 2985, 'nama_desa_kelurahan' => 'Warungboto'],
            ['id_desa_kelurahan' => 43330, 'id_kecamatan' => 2985, 'nama_desa_kelurahan' => 'Mujamuju'],
            ['id_desa_kelurahan' => 43331, 'id_kecamatan' => 2985, 'nama_desa_kelurahan' => 'Pandeyan'],
            ['id_desa_kelurahan' => 43332, 'id_kecamatan' => 2985, 'nama_desa_kelurahan' => 'Sorowajan'],
            ['id_desa_kelurahan' => 43333, 'id_kecamatan' => 2986, 'nama_desa_kelurahan' => 'Purbayan'],
            ['id_desa_kelurahan' => 43334, 'id_kecamatan' => 2986, 'nama_desa_kelurahan' => 'Singosaren'],
            ['id_desa_kelurahan' => 43335, 'id_kecamatan' => 2986, 'nama_desa_kelurahan' => 'Prenggan'],
            ['id_desa_kelurahan' => 43336, 'id_kecamatan' => 2987, 'nama_desa_kelurahan' => 'Demangan'],
            ['id_desa_kelurahan' => 43337, 'id_kecamatan' => 2987, 'nama_desa_kelurahan' => 'Baciro'],
            ['id_desa_kelurahan' => 43338, 'id_kecamatan' => 2987, 'nama_desa_kelurahan' => 'Klumpit'],
            ['id_desa_kelurahan' => 43339, 'id_kecamatan' => 2988, 'nama_desa_kelurahan' => 'Tegalpanggung'],
            ['id_desa_kelurahan' => 43340, 'id_kecamatan' => 2988, 'nama_desa_kelurahan' => 'Bausasran'],
            ['id_desa_kelurahan' => 43341, 'id_kecamatan' => 2988, 'nama_desa_kelurahan' => 'Kricak'],
            ['id_desa_kelurahan' => 43342, 'id_kecamatan' => 2989, 'nama_desa_kelurahan' => 'Gunungketur'],
            ['id_desa_kelurahan' => 43343, 'id_kecamatan' => 2989, 'nama_desa_kelurahan' => 'Purwokinanti'],
            ['id_desa_kelurahan' => 43344, 'id_kecamatan' => 2990, 'nama_desa_kelurahan' => 'Ngupasan'],
            ['id_desa_kelurahan' => 43345, 'id_kecamatan' => 2990, 'nama_desa_kelurahan' => 'Gondomanan'],
            ['id_desa_kelurahan' => 43346, 'id_kecamatan' => 2990, 'nama_desa_kelurahan' => 'Prawirodirjan'],
            ['id_desa_kelurahan' => 43347, 'id_kecamatan' => 2991, 'nama_desa_kelurahan' => 'Ngampilan'],
            ['id_desa_kelurahan' => 43348, 'id_kecamatan' => 2991, 'nama_desa_kelurahan' => 'Notoprajan'],
            ['id_desa_kelurahan' => 43349, 'id_kecamatan' => 2991, 'nama_desa_kelurahan' => 'Patangpuluhan'],
            ['id_desa_kelurahan' => 43350, 'id_kecamatan' => 2992, 'nama_desa_kelurahan' => 'Wirobrajan'],
            ['id_desa_kelurahan' => 43351, 'id_kecamatan' => 2992, 'nama_desa_kelurahan' => 'Gedongkiwo'],
            ['id_desa_kelurahan' => 43352, 'id_kecamatan' => 2992, 'nama_desa_kelurahan' => 'Bener'],
            ['id_desa_kelurahan' => 43353, 'id_kecamatan' => 2993, 'nama_desa_kelurahan' => 'Sosromenduran'],
            ['id_desa_kelurahan' => 43354, 'id_kecamatan' => 2993, 'nama_desa_kelurahan' => 'Pringgokusuman'],
            ['id_desa_kelurahan' => 43355, 'id_kecamatan' => 2994, 'nama_desa_kelurahan' => 'Bumijo'],
            ['id_desa_kelurahan' => 43356, 'id_kecamatan' => 2994, 'nama_desa_kelurahan' => 'Cokrodiningratan'],
            ['id_desa_kelurahan' => 43357, 'id_kecamatan' => 2994, 'nama_desa_kelurahan' => 'Jetis'],
            ['id_desa_kelurahan' => 43358, 'id_kecamatan' => 2995, 'nama_desa_kelurahan' => 'Tegalrejo'],
            ['id_desa_kelurahan' => 43359, 'id_kecamatan' => 2995, 'nama_desa_kelurahan' => 'Kembang'],
            ['id_desa_kelurahan' => 43360, 'id_kecamatan' => 2995, 'nama_desa_kelurahan' => 'Karangwaru'],
            ['id_desa_kelurahan' => 43361, 'id_kecamatan' => 2995, 'nama_desa_kelurahan' => 'Suryatmajan'],

            // Gunungkidul (id: 213, 18 kecamatan, 144 desa)
            ['id_desa_kelurahan' => 43362, 'id_kecamatan' => 2996, 'nama_desa_kelurahan' => 'Giricahyo'],
            ['id_desa_kelurahan' => 43363, 'id_kecamatan' => 2996, 'nama_desa_kelurahan' => 'Panggang'],
            ['id_desa_kelurahan' => 43364, 'id_kecamatan' => 2996, 'nama_desa_kelurahan' => 'Giriwungu'],
            ['id_desa_kelurahan' => 43365, 'id_kecamatan' => 2996, 'nama_desa_kelurahan' => 'Girisuko'],
            ['id_desa_kelurahan' => 43366, 'id_kecamatan' => 2996, 'nama_desa_kelurahan' => 'Girisekar'],
            ['id_desa_kelurahan' => 43367, 'id_kecamatan' => 2996, 'nama_desa_kelurahan' => 'Giritirto'],
            ['id_desa_kelurahan' => 43368, 'id_kecamatan' => 2996, 'nama_desa_kelurahan' => 'Girijati'],
            ['id_desa_kelurahan' => 43369, 'id_kecamatan' => 2996, 'nama_desa_kelurahan' => 'Giripurwo'],
            ['id_desa_kelurahan' => 43370, 'id_kecamatan' => 2997, 'nama_desa_kelurahan' => 'Girikarto'],
            ['id_desa_kelurahan' => 43371, 'id_kecamatan' => 2997, 'nama_desa_kelurahan' => 'Purwosari'],
            ['id_desa_kelurahan' => 43372, 'id_kecamatan' => 2997, 'nama_desa_kelurahan' => 'Girisari'],
            ['id_desa_kelurahan' => 43373, 'id_kecamatan' => 2997, 'nama_desa_kelurahan' => 'Giriharjo'],
            ['id_desa_kelurahan' => 43374, 'id_kecamatan' => 2997, 'nama_desa_kelurahan' => 'Giritunggal'],
            ['id_desa_kelurahan' => 43375, 'id_kecamatan' => 2997, 'nama_desa_kelurahan' => 'Giriwarno'],
            ['id_desa_kelurahan' => 43376, 'id_kecamatan' => 2997, 'nama_desa_kelurahan' => 'Girikaryo'],
            ['id_desa_kelurahan' => 43377, 'id_kecamatan' => 2997, 'nama_desa_kelurahan' => 'Giriloyo'],
            ['id_desa_kelurahan' => 43378, 'id_kecamatan' => 2998, 'nama_desa_kelurahan' => 'Giritontro'],
            ['id_desa_kelurahan' => 43379, 'id_kecamatan' => 2998, 'nama_desa_kelurahan' => 'Paliyan'],
            ['id_desa_kelurahan' => 43380, 'id_kecamatan' => 2998, 'nama_desa_kelurahan' => 'Girisato'],
            ['id_desa_kelurahan' => 43381, 'id_kecamatan' => 2998, 'nama_desa_kelurahan' => 'Giriwetan'],
            ['id_desa_kelurahan' => 43382, 'id_kecamatan' => 2998, 'nama_desa_kelurahan' => 'Girimulyo'],
            ['id_desa_kelurahan' => 43383, 'id_kecamatan' => 2998, 'nama_desa_kelurahan' => 'Girikaton'],
            ['id_desa_kelurahan' => 43384, 'id_kecamatan' => 2998, 'nama_desa_kelurahan' => 'Giriwinangun'],
            ['id_desa_kelurahan' => 43385, 'id_kecamatan' => 2998, 'nama_desa_kelurahan' => 'Girisiddo'],
            ['id_desa_kelurahan' => 43386, 'id_kecamatan' => 2999, 'nama_desa_kelurahan' => 'Saptosari'],
            ['id_desa_kelurahan' => 43387, 'id_kecamatan' => 2999, 'nama_desa_kelurahan' => 'Kanigoro'],
            ['id_desa_kelurahan' => 43388, 'id_kecamatan' => 2999, 'nama_desa_kelurahan' => 'Kedungpoh'],
            ['id_desa_kelurahan' => 43389, 'id_kecamatan' => 2999, 'nama_desa_kelurahan' => 'Nglindur'],
            ['id_desa_kelurahan' => 43390, 'id_kecamatan' => 2999, 'nama_desa_kelurahan' => 'Planjan'],
            ['id_desa_kelurahan' => 43391, 'id_kecamatan' => 2999, 'nama_desa_kelurahan' => 'Songbanyu'],
            ['id_desa_kelurahan' => 43392, 'id_kecamatan' => 2999, 'nama_desa_kelurahan' => 'Jetis'],
            ['id_desa_kelurahan' => 43393, 'id_kecamatan' => 2999, 'nama_desa_kelurahan' => 'Kepek'],
            ['id_desa_kelurahan' => 43394, 'id_kecamatan' => 3000, 'nama_desa_kelurahan' => 'Girisuci'],
            ['id_desa_kelurahan' => 43395, 'id_kecamatan' => 3000, 'nama_desa_kelurahan' => 'Pucung'],
            ['id_desa_kelurahan' => 43396, 'id_kecamatan' => 3000, 'nama_desa_kelurahan' => 'Girijaya'],
            ['id_desa_kelurahan' => 43397, 'id_kecamatan' => 3000, 'nama_desa_kelurahan' => 'Girimulya'],
            ['id_desa_kelurahan' => 43398, 'id_kecamatan' => 3000, 'nama_desa_kelurahan' => 'Giriwarno'],
            ['id_desa_kelurahan' => 43399, 'id_kecamatan' => 3000, 'nama_desa_kelurahan' => 'Giripeni'],
            ['id_desa_kelurahan' => 43400, 'id_kecamatan' => 3000, 'nama_desa_kelurahan' => 'Girikarya'],
            ['id_desa_kelurahan' => 43401, 'id_kecamatan' => 3000, 'nama_desa_kelurahan' => 'Girihardjo'],
            ['id_desa_kelurahan' => 43402, 'id_kecamatan' => 3001, 'nama_desa_kelurahan' => 'Tepus'],
            ['id_desa_kelurahan' => 43403, 'id_kecamatan' => 3001, 'nama_desa_kelurahan' => 'Purwodadi'],
            ['id_desa_kelurahan' => 43404, 'id_kecamatan' => 3001, 'nama_desa_kelurahan' => 'Sidoharjo'],
            ['id_desa_kelurahan' => 43405, 'id_kecamatan' => 3001, 'nama_desa_kelurahan' => 'Tepus'],
            ['id_desa_kelurahan' => 43406, 'id_kecamatan' => 3001, 'nama_desa_kelurahan' => 'Giripanggung'],
            ['id_desa_kelurahan' => 43407, 'id_kecamatan' => 3001, 'nama_desa_kelurahan' => 'Giritirta'],
            ['id_desa_kelurahan' => 43408, 'id_kecamatan' => 3001, 'nama_desa_kelurahan' => 'Giriwedoro'],
            ['id_desa_kelurahan' => 43409, 'id_kecamatan' => 3001, 'nama_desa_kelurahan' => 'Giripurwo'],
            ['id_desa_kelurahan' => 43410, 'id_kecamatan' => 3002, 'nama_desa_kelurahan' => 'Tanjungsari'],
            ['id_desa_kelurahan' => 43411, 'id_kecamatan' => 3002, 'nama_desa_kelurahan' => 'Banjaroyo'],
            ['id_desa_kelurahan' => 43412, 'id_kecamatan' => 3002, 'nama_desa_kelurahan' => 'Kemadang'],
            ['id_desa_kelurahan' => 43413, 'id_kecamatan' => 3002, 'nama_desa_kelurahan' => 'Ngestirejo'],
            ['id_desa_kelurahan' => 43414, 'id_kecamatan' => 3002, 'nama_desa_kelurahan' => 'Kemiri'],
            ['id_desa_kelurahan' => 43415, 'id_kecamatan' => 3002, 'nama_desa_kelurahan' => 'Tanjungsari'],
            ['id_desa_kelurahan' => 43416, 'id_kecamatan' => 3002, 'nama_desa_kelurahan' => 'Giripanggung'],
            ['id_desa_kelurahan' => 43417, 'id_kecamatan' => 3002, 'nama_desa_kelurahan' => 'Girikarto'],
            ['id_desa_kelurahan' => 43418, 'id_kecamatan' => 3003, 'nama_desa_kelurahan' => 'Rongkop'],
            ['id_desa_kelurahan' => 43419, 'id_kecamatan' => 3003, 'nama_desa_kelurahan' => 'Giriasih'],
            ['id_desa_kelurahan' => 43420, 'id_kecamatan' => 3003, 'nama_desa_kelurahan' => 'Giriwetan'],
            ['id_desa_kelurahan' => 43421, 'id_kecamatan' => 3003, 'nama_desa_kelurahan' => 'Girikarto'],
            ['id_desa_kelurahan' => 43422, 'id_kecamatan' => 3003, 'nama_desa_kelurahan' => 'Girijaya'],
            ['id_desa_kelurahan' => 43423, 'id_kecamatan' => 3003, 'nama_desa_kelurahan' => 'Giriloyo'],
            ['id_desa_kelurahan' => 43424, 'id_kecamatan' => 3003, 'nama_desa_kelurahan' => 'Giripurwo'],
            ['id_desa_kelurahan' => 43425, 'id_kecamatan' => 3003, 'nama_desa_kelurahan' => 'Giriwungu'],
            ['id_desa_kelurahan' => 43426, 'id_kecamatan' => 3004, 'nama_desa_kelurahan' => 'Semin'],
            ['id_desa_kelurahan' => 43427, 'id_kecamatan' => 3004, 'nama_desa_kelurahan' => 'Candirejo'],
            ['id_desa_kelurahan' => 43428, 'id_kecamatan' => 3004, 'nama_desa_kelurahan' => 'Kemejing'],
            ['id_desa_kelurahan' => 43429, 'id_kecamatan' => 3004, 'nama_desa_kelurahan' => 'Pundungsari'],
            ['id_desa_kelurahan' => 43430, 'id_kecamatan' => 3004, 'nama_desa_kelurahan' => 'Rejosari'],
            ['id_desa_kelurahan' => 43431, 'id_kecamatan' => 3004, 'nama_desa_kelurahan' => 'Tambak'],
            ['id_desa_kelurahan' => 43432, 'id_kecamatan' => 3004, 'nama_desa_kelurahan' => 'Sumberrejo'],
            ['id_desa_kelurahan' => 43433, 'id_kecamatan' => 3004, 'nama_desa_kelurahan' => 'Karangmojo'],
            ['id_desa_kelurahan' => 43434, 'id_kecamatan' => 3005, 'nama_desa_kelurahan' => 'Ngawen'],
            ['id_desa_kelurahan' => 43435, 'id_kecamatan' => 3005, 'nama_desa_kelurahan' => 'Beji'],
            ['id_desa_kelurahan' => 43436, 'id_kecamatan' => 3005, 'nama_desa_kelurahan' => 'Banyusoco'],
            ['id_desa_kelurahan' => 43437, 'id_kecamatan' => 3005, 'nama_desa_kelurahan' => 'Wates'],
            ['id_desa_kelurahan' => 43438, 'id_kecamatan' => 3005, 'nama_desa_kelurahan' => 'Sampang'],
            ['id_desa_kelurahan' => 43439, 'id_kecamatan' => 3005, 'nama_desa_kelurahan' => 'Katongan'],
            ['id_desa_kelurahan' => 43440, 'id_kecamatan' => 3005, 'nama_desa_kelurahan' => 'Tancep'],
            ['id_desa_kelurahan' => 43441, 'id_kecamatan' => 3005, 'nama_desa_kelurahan' => 'Ngloro'],
            ['id_desa_kelurahan' => 43442, 'id_kecamatan' => 3006, 'nama_desa_kelurahan' => 'Playen'],
            ['id_desa_kelurahan' => 43443, 'id_kecamatan' => 3006, 'nama_desa_kelurahan' => 'Banyusoco'],
            ['id_desa_kelurahan' => 43444, 'id_kecamatan' => 3006, 'nama_desa_kelurahan' => 'Banaran'],
            ['id_desa_kelurahan' => 43445, 'id_kecamatan' => 3006, 'nama_desa_kelurahan' => 'Ngleri'],
            ['id_desa_kelurahan' => 43446, 'id_kecamatan' => 3006, 'nama_desa_kelurahan' => 'Gading'],
            ['id_desa_kelurahan' => 43447, 'id_kecamatan' => 3006, 'nama_desa_kelurahan' => 'Plembono'],
            ['id_desa_kelurahan' => 43448, 'id_kecamatan' => 3006, 'nama_desa_kelurahan' => 'Ngawu'],
            ['id_desa_kelurahan' => 43449, 'id_kecamatan' => 3006, 'nama_desa_kelurahan' => 'Logandeng'],
            ['id_desa_kelurahan' => 43450, 'id_kecamatan' => 3007, 'nama_desa_kelurahan' => 'Patuk'],
            ['id_desa_kelurahan' => 43451, 'id_kecamatan' => 3007, 'nama_desa_kelurahan' => 'Bunder'],
            ['id_desa_kelurahan' => 43452, 'id_kecamatan' => 3007, 'nama_desa_kelurahan' => 'Ngoro-oro'],
            ['id_desa_kelurahan' => 43453, 'id_kecamatan' => 3007, 'nama_desa_kelurahan' => 'Nglanggeran'],
            ['id_desa_kelurahan' => 43454, 'id_kecamatan' => 3007, 'nama_desa_kelurahan' => 'Pengkok'],
            ['id_desa_kelurahan' => 43455, 'id_kecamatan' => 3007, 'nama_desa_kelurahan' => 'Salam'],
            ['id_desa_kelurahan' => 43456, 'id_kecamatan' => 3007, 'nama_desa_kelurahan' => 'Terbah'],
            ['id_desa_kelurahan' => 43457, 'id_kecamatan' => 3007, 'nama_desa_kelurahan' => 'Putat'],
            ['id_desa_kelurahan' => 43458, 'id_kecamatan' => 3008, 'nama_desa_kelurahan' => 'Nglipar'],
            ['id_desa_kelurahan' => 43459, 'id_kecamatan' => 3008, 'nama_desa_kelurahan' => 'Kedungkeris'],
            ['id_desa_kelurahan' => 43460, 'id_kecamatan' => 3008, 'nama_desa_kelurahan' => 'Pilangrejo'],
            ['id_desa_kelurahan' => 43461, 'id_kecamatan' => 3008, 'nama_desa_kelurahan' => 'Nglipar'],
            ['id_desa_kelurahan' => 43462, 'id_kecamatan' => 3008, 'nama_desa_kelurahan' => 'Pengkol'],
            ['id_desa_kelurahan' => 43463, 'id_kecamatan' => 3008, 'nama_desa_kelurahan' => 'Kedungpoh'],
            ['id_desa_kelurahan' => 43464, 'id_kecamatan' => 3008, 'nama_desa_kelurahan' => 'Katongan'],
            ['id_desa_kelurahan' => 43465, 'id_kecamatan' => 3008, 'nama_desa_kelurahan' => 'Natah'],
            ['id_desa_kelurahan' => 43466, 'id_kecamatan' => 3009, 'nama_desa_kelurahan' => 'Gedangsari'],
            ['id_desa_kelurahan' => 43467, 'id_kecamatan' => 3009, 'nama_desa_kelurahan' => 'Hargomulyo'],
            ['id_desa_kelurahan' => 43468, 'id_kecamatan' => 3009, 'nama_desa_kelurahan' => 'Sampang'],
            ['id_desa_kelurahan' => 43469, 'id_kecamatan' => 3009, 'nama_desa_kelurahan' => 'Mertelu'],
            ['id_desa_kelurahan' => 43470, 'id_kecamatan' => 3009, 'nama_desa_kelurahan' => 'Tegalrejo'],
            ['id_desa_kelurahan' => 43471, 'id_kecamatan' => 3009, 'nama_desa_kelurahan' => 'Watugajah'],
            ['id_desa_kelurahan' => 43472, 'id_kecamatan' => 3009, 'nama_desa_kelurahan' => 'Giripurwo'],
            ['id_desa_kelurahan' => 43473, 'id_kecamatan' => 3009, 'nama_desa_kelurahan' => 'Giriwetan'],
            ['id_desa_kelurahan' => 43474, 'id_kecamatan' => 3010, 'nama_desa_kelurahan' => 'Girisubo'],
            ['id_desa_kelurahan' => 43475, 'id_kecamatan' => 3010, 'nama_desa_kelurahan' => 'Jepitu'],
            ['id_desa_kelurahan' => 43476, 'id_kecamatan' => 3010, 'nama_desa_kelurahan' => 'Karangawen'],
            ['id_desa_kelurahan' => 43477, 'id_kecamatan' => 3010, 'nama_desa_kelurahan' => 'Nglindur'],
            ['id_desa_kelurahan' => 43478, 'id_kecamatan' => 3010, 'nama_desa_kelurahan' => 'Tileng'],
            ['id_desa_kelurahan' => 43479, 'id_kecamatan' => 3010, 'nama_desa_kelurahan' => 'Songbanyu'],
            ['id_desa_kelurahan' => 43480, 'id_kecamatan' => 3010, 'nama_desa_kelurahan' => 'Girikarto'],
            ['id_desa_kelurahan' => 43481, 'id_kecamatan' => 3010, 'nama_desa_kelurahan' => 'Giriwetan'],
            ['id_desa_kelurahan' => 43482, 'id_kecamatan' => 3011, 'nama_desa_kelurahan' => 'Saptosari'],
            ['id_desa_kelurahan' => 43483, 'id_kecamatan' => 3011, 'nama_desa_kelurahan' => 'Krambilsawit'],
            ['id_desa_kelurahan' => 43484, 'id_kecamatan' => 3011, 'nama_desa_kelurahan' => 'Panggul'],
            ['id_desa_kelurahan' => 43485, 'id_kecamatan' => 3011, 'nama_desa_kelurahan' => 'Pringombo'],
            ['id_desa_kelurahan' => 43486, 'id_kecamatan' => 3011, 'nama_desa_kelurahan' => 'Rejosari'],
            ['id_desa_kelurahan' => 43487, 'id_kecamatan' => 3011, 'nama_desa_kelurahan' => 'Jetis'],
            ['id_desa_kelurahan' => 43488, 'id_kecamatan' => 3011, 'nama_desa_kelurahan' => 'Kanigoro'],
            ['id_desa_kelurahan' => 43489, 'id_kecamatan' => 3011, 'nama_desa_kelurahan' => 'Planjan'],
            ['id_desa_kelurahan' => 43490, 'id_kecamatan' => 3012, 'nama_desa_kelurahan' => 'Karangmojo'],
            ['id_desa_kelurahan' => 43491, 'id_kecamatan' => 3012, 'nama_desa_kelurahan' => 'Bejiharjo'],
            ['id_desa_kelurahan' => 43492, 'id_kecamatan' => 3012, 'nama_desa_kelurahan' => 'Jatiayu'],
            ['id_desa_kelurahan' => 43493, 'id_kecamatan' => 3012, 'nama_desa_kelurahan' => 'Karangrejek'],
            ['id_desa_kelurahan' => 43494, 'id_kecamatan' => 3012, 'nama_desa_kelurahan' => 'Ngawis'],
            ['id_desa_kelurahan' => 43495, 'id_kecamatan' => 3012, 'nama_desa_kelurahan' => 'Wiladeg'],
            ['id_desa_kelurahan' => 43496, 'id_kecamatan' => 3012, 'nama_desa_kelurahan' => 'Kelor'],
            ['id_desa_kelurahan' => 43497, 'id_kecamatan' => 3012, 'nama_desa_kelurahan' => 'Bendungan'],
            ['id_desa_kelurahan' => 43498, 'id_kecamatan' => 3013, 'nama_desa_kelurahan' => 'Wonosari'],
            ['id_desa_kelurahan' => 43499, 'id_kecamatan' => 3013, 'nama_desa_kelurahan' => 'Siyono'],
            ['id_desa_kelurahan' => 43500, 'id_kecamatan' => 3013, 'nama_desa_kelurahan' => 'Karangtengah'],
            ['id_desa_kelurahan' => 43501, 'id_kecamatan' => 3013, 'nama_desa_kelurahan' => 'Kepek'],
            ['id_desa_kelurahan' => 43502, 'id_kecamatan' => 3013, 'nama_desa_kelurahan' => 'Siraman'],
            ['id_desa_kelurahan' => 43503, 'id_kecamatan' => 3013, 'nama_desa_kelurahan' => 'Wuni'],
            ['id_desa_kelurahan' => 43504, 'id_kecamatan' => 3013, 'nama_desa_kelurahan' => 'Pulutan'],
            ['id_desa_kelurahan' => 43505, 'id_kecamatan' => 3013, 'nama_desa_kelurahan' => 'Mulo'],

            // Kulon Progo (id: 214, 12 kecamatan, 88 desa)
            ['id_desa_kelurahan' => 43506, 'id_kecamatan' => 3014, 'nama_desa_kelurahan' => 'Palihan'],
            ['id_desa_kelurahan' => 43507, 'id_kecamatan' => 3014, 'nama_desa_kelurahan' => 'Temon'],
            ['id_desa_kelurahan' => 43508, 'id_kecamatan' => 3014, 'nama_desa_kelurahan' => 'Sindutan'],
            ['id_desa_kelurahan' => 43509, 'id_kecamatan' => 3014, 'nama_desa_kelurahan' => 'Kaligondang'],
            ['id_desa_kelurahan' => 43510, 'id_kecamatan' => 3014, 'nama_desa_kelurahan' => 'Karangwuluh'],
            ['id_desa_kelurahan' => 43511, 'id_kecamatan' => 3014, 'nama_desa_kelurahan' => 'Kebonrejo'],
            ['id_desa_kelurahan' => 43512, 'id_kecamatan' => 3014, 'nama_desa_kelurahan' => 'Janten'],
            ['id_desa_kelurahan' => 43513, 'id_kecamatan' => 3014, 'nama_desa_kelurahan' => 'Plumbon'],
            ['id_desa_kelurahan' => 43514, 'id_kecamatan' => 3015, 'nama_desa_kelurahan' => 'Margosari'],
            ['id_desa_kelurahan' => 43515, 'id_kecamatan' => 3015, 'nama_desa_kelurahan' => 'Wates'],
            ['id_desa_kelurahan' => 43516, 'id_kecamatan' => 3015, 'nama_desa_kelurahan' => 'Triharjo'],
            ['id_desa_kelurahan' => 43517, 'id_kecamatan' => 3015, 'nama_desa_kelurahan' => 'Sogan'],
            ['id_desa_kelurahan' => 43518, 'id_kecamatan' => 3015, 'nama_desa_kelurahan' => 'Giripeni'],
            ['id_desa_kelurahan' => 43519, 'id_kecamatan' => 3015, 'nama_desa_kelurahan' => 'Karangwuni'],
            ['id_desa_kelurahan' => 43520, 'id_kecamatan' => 3015, 'nama_desa_kelurahan' => 'Nomporejo'],
            ['id_desa_kelurahan' => 43521, 'id_kecamatan' => 3015, 'nama_desa_kelurahan' => 'Bendungan'],
            ['id_desa_kelurahan' => 43522, 'id_kecamatan' => 3016, 'nama_desa_kelurahan' => 'Bugel'],
            ['id_desa_kelurahan' => 43523, 'id_kecamatan' => 3016, 'nama_desa_kelurahan' => 'Panjatan'],
            ['id_desa_kelurahan' => 43524, 'id_kecamatan' => 3016, 'nama_desa_kelurahan' => 'Cerme'],
            ['id_desa_kelurahan' => 43525, 'id_kecamatan' => 3016, 'nama_desa_kelurahan' => 'Krembangan'],
            ['id_desa_kelurahan' => 43526, 'id_kecamatan' => 3016, 'nama_desa_kelurahan' => 'Gotakan'],
            ['id_desa_kelurahan' => 43527, 'id_kecamatan' => 3016, 'nama_desa_kelurahan' => 'Depokan'],
            ['id_desa_kelurahan' => 43528, 'id_kecamatan' => 3016, 'nama_desa_kelurahan' => 'Kanoman'],
            ['id_desa_kelurahan' => 43529, 'id_kecamatan' => 3016, 'nama_desa_kelurahan' => 'Pleret'],
            ['id_desa_kelurahan' => 43530, 'id_kecamatan' => 3017, 'nama_desa_kelurahan' => 'Galur'],
            ['id_desa_kelurahan' => 43531, 'id_kecamatan' => 3017, 'nama_desa_kelurahan' => 'Brosot'],
            ['id_desa_kelurahan' => 43532, 'id_kecamatan' => 3017, 'nama_desa_kelurahan' => 'Kranggan'],
            ['id_desa_kelurahan' => 43533, 'id_kecamatan' => 3017, 'nama_desa_kelurahan' => 'Pandowan'],
            ['id_desa_kelurahan' => 43534, 'id_kecamatan' => 3017, 'nama_desa_kelurahan' => 'Karangsewu'],
            ['id_desa_kelurahan' => 43535, 'id_kecamatan' => 3017, 'nama_desa_kelurahan' => 'Ngentakrejo'],
            ['id_desa_kelurahan' => 43536, 'id_kecamatan' => 3017, 'nama_desa_kelurahan' => 'Tawangrejo'],
            ['id_desa_kelurahan' => 43537, 'id_kecamatan' => 3017, 'nama_desa_kelurahan' => 'Banjararum'],
            ['id_desa_kelurahan' => 43538, 'id_kecamatan' => 3018, 'nama_desa_kelurahan' => 'Lendah'],
            ['id_desa_kelurahan' => 43539, 'id_kecamatan' => 3018, 'nama_desa_kelurahan' => 'Wahyuharjo'],
            ['id_desa_kelurahan' => 43540, 'id_kecamatan' => 3018, 'nama_desa_kelurahan' => 'Bumirejo'],
            ['id_desa_kelurahan' => 43541, 'id_kecamatan' => 3018, 'nama_desa_kelurahan' => 'Jatirejo'],
            ['id_desa_kelurahan' => 43542, 'id_kecamatan' => 3018, 'nama_desa_kelurahan' => 'Sidorejo'],
            ['id_desa_kelurahan' => 43543, 'id_kecamatan' => 3018, 'nama_desa_kelurahan' => 'Gulurejo'],
            ['id_desa_kelurahan' => 43544, 'id_kecamatan' => 3018, 'nama_desa_kelurahan' => 'Banguncipto'],
            ['id_desa_kelurahan' => 43545, 'id_kecamatan' => 3018, 'nama_desa_kelurahan' => 'Ngabeyan'],
            ['id_desa_kelurahan' => 43546, 'id_kecamatan' => 3019, 'nama_desa_kelurahan' => 'Sentolo'],
            ['id_desa_kelurahan' => 43547, 'id_kecamatan' => 3019, 'nama_desa_kelurahan' => 'Sukoreno'],
            ['id_desa_kelurahan' => 43548, 'id_kecamatan' => 3019, 'nama_desa_kelurahan' => 'Kembang'],
            ['id_desa_kelurahan' => 43549, 'id_kecamatan' => 3019, 'nama_desa_kelurahan' => 'Banguncipto'],
            ['id_desa_kelurahan' => 43550, 'id_kecamatan' => 3019, 'nama_desa_kelurahan' => 'Salamrejo'],
            ['id_desa_kelurahan' => 43551, 'id_kecamatan' => 3019, 'nama_desa_kelurahan' => 'Kaliagung'],
            ['id_desa_kelurahan' => 43552, 'id_kecamatan' => 3019, 'nama_desa_kelurahan' => 'Demangrejo'],
            ['id_desa_kelurahan' => 43553, 'id_kecamatan' => 3019, 'nama_desa_kelurahan' => 'Srikandi'],
            ['id_desa_kelurahan' => 43554, 'id_kecamatan' => 3020, 'nama_desa_kelurahan' => 'Pengasih'],
            ['id_desa_kelurahan' => 43555, 'id_kecamatan' => 3020, 'nama_desa_kelurahan' => 'Sidomulyo'],
            ['id_desa_kelurahan' => 43556, 'id_kecamatan' => 3020, 'nama_desa_kelurahan' => 'Sendangmulyo'],
            ['id_desa_kelurahan' => 43557, 'id_kecamatan' => 3020, 'nama_desa_kelurahan' => 'Karangtengah'],
            ['id_desa_kelurahan' => 43558, 'id_kecamatan' => 3020, 'nama_desa_kelurahan' => 'Margosari'],
            ['id_desa_kelurahan' => 43559, 'id_kecamatan' => 3020, 'nama_desa_kelurahan' => 'Kedungsari'],
            ['id_desa_kelurahan' => 43560, 'id_kecamatan' => 3020, 'nama_desa_kelurahan' => 'Pengasihrejo'],
            ['id_desa_kelurahan' => 43561, 'id_kecamatan' => 3020, 'nama_desa_kelurahan' => 'Tawangsari'],
            ['id_desa_kelurahan' => 43562, 'id_kecamatan' => 3021, 'nama_desa_kelurahan' => 'Kokap'],
            ['id_desa_kelurahan' => 43563, 'id_kecamatan' => 3021, 'nama_desa_kelurahan' => 'Hargosari'],
            ['id_desa_kelurahan' => 43564, 'id_kecamatan' => 3021, 'nama_desa_kelurahan' => 'Kalirejo'],
            ['id_desa_kelurahan' => 43565, 'id_kecamatan' => 3021, 'nama_desa_kelurahan' => 'Banjarsari'],
            ['id_desa_kelurahan' => 43566, 'id_kecamatan' => 3021, 'nama_desa_kelurahan' => 'Triharjo'],
            ['id_desa_kelurahan' => 43567, 'id_kecamatan' => 3021, 'nama_desa_kelurahan' => 'Sendangrejo'],
            ['id_desa_kelurahan' => 43568, 'id_kecamatan' => 3021, 'nama_desa_kelurahan' => 'Giripurwo'],
            ['id_desa_kelurahan' => 43569, 'id_kecamatan' => 3021, 'nama_desa_kelurahan' => 'Madigondo'],
            ['id_desa_kelurahan' => 43570, 'id_kecamatan' => 3022, 'nama_desa_kelurahan' => 'Girimulyo'],
            ['id_desa_kelurahan' => 43571, 'id_kecamatan' => 3022, 'nama_desa_kelurahan' => 'Purwosari'],
            ['id_desa_kelurahan' => 43572, 'id_kecamatan' => 3022, 'nama_desa_kelurahan' => 'Gerbosari'],
            ['id_desa_kelurahan' => 43573, 'id_kecamatan' => 3022, 'nama_desa_kelurahan' => 'Jatisarono'],
            ['id_desa_kelurahan' => 43574, 'id_kecamatan' => 3022, 'nama_desa_kelurahan' => 'Ngargosari'],
            ['id_desa_kelurahan' => 43575, 'id_kecamatan' => 3022, 'nama_desa_kelurahan' => 'Pagerharjo'],
            ['id_desa_kelurahan' => 43576, 'id_kecamatan' => 3022, 'nama_desa_kelurahan' => 'Kembangrejo'],
            ['id_desa_kelurahan' => 43577, 'id_kecamatan' => 3022, 'nama_desa_kelurahan' => 'Sidoharjo'],
            ['id_desa_kelurahan' => 43578, 'id_kecamatan' => 3023, 'nama_desa_kelurahan' => 'Nanggulan'],
            ['id_desa_kelurahan' => 43579, 'id_kecamatan' => 3023, 'nama_desa_kelurahan' => 'Jatiwangsan'],
            ['id_desa_kelurahan' => 43580, 'id_kecamatan' => 3023, 'nama_desa_kelurahan' => 'Donorejo'],
            ['id_desa_kelurahan' => 43581, 'id_kecamatan' => 3023, 'nama_desa_kelurahan' => 'Kembangmulyo'],
            ['id_desa_kelurahan' => 43582, 'id_kecamatan' => 3023, 'nama_desa_kelurahan' => 'Sukoharjo'],
            ['id_desa_kelurahan' => 43583, 'id_kecamatan' => 3023, 'nama_desa_kelurahan' => 'Wonosidi'],
            ['id_desa_kelurahan' => 43584, 'id_kecamatan' => 3023, 'nama_desa_kelurahan' => 'Banyuroto'],
            ['id_desa_kelurahan' => 43585, 'id_kecamatan' => 3023, 'nama_desa_kelurahan' => 'Tanjungsari'],
            ['id_desa_kelurahan' => 43586, 'id_kecamatan' => 3024, 'nama_desa_kelurahan' => 'Kalibawang'],
            ['id_desa_kelurahan' => 43587, 'id_kecamatan' => 3024, 'nama_desa_kelurahan' => 'Banjaroyo'],
            ['id_desa_kelurahan' => 43588, 'id_kecamatan' => 3024, 'nama_desa_kelurahan' => 'Banjarasri'],
            ['id_desa_kelurahan' => 43589, 'id_kecamatan' => 3024, 'nama_desa_kelurahan' => 'Banjararum'],
            ['id_desa_kelurahan' => 43590, 'id_kecamatan' => 3024, 'nama_desa_kelurahan' => 'Banjarsari'],
            ['id_desa_kelurahan' => 43591, 'id_kecamatan' => 3024, 'nama_desa_kelurahan' => 'Tegalsari'],
            ['id_desa_kelurahan' => 43592, 'id_kecamatan' => 3024, 'nama_desa_kelurahan' => 'Sidomulyo'],
            ['id_desa_kelurahan' => 43593, 'id_kecamatan' => 3025, 'nama_desa_kelurahan' => 'Samigaluh'],
            ['id_desa_kelurahan' => 43594, 'id_kecamatan' => 3025, 'nama_desa_kelurahan' => 'Purwoharjo'],
            ['id_desa_kelurahan' => 43595, 'id_kecamatan' => 3025, 'nama_desa_kelurahan' => 'Sidoharjo'],
            ['id_desa_kelurahan' => 43596, 'id_kecamatan' => 3025, 'nama_desa_kelurahan' => 'Ngargosari'],
            ['id_desa_kelurahan' => 43597, 'id_kecamatan' => 3025, 'nama_desa_kelurahan' => 'Kebonharjo'],
            ['id_desa_kelurahan' => 43598, 'id_kecamatan' => 3025, 'nama_desa_kelurahan' => 'Tawangsari'],
            ['id_desa_kelurahan' => 43599, 'id_kecamatan' => 3025, 'nama_desa_kelurahan' => 'Sukosari'],
            ['id_desa_kelurahan' => 43600, 'id_kecamatan' => 3025, 'nama_desa_kelurahan' => 'Banjarharjo']
        ];

        foreach ($desaKelurahans as $desaKelurahan) {
            DesaKelurahan::create($desaKelurahan);
        }
    }
}
